
export type Course = {
  id: string; // e.g. ap_us_history
  slug: string; // e.g. ap-us-history
  name: string; // e.g. AP US History
  icon: string; // component name, emoji, or URL path
  description: string;
  subject: string;
  examDate: string;
  comingSoon?: boolean;
  abbreviations?: string[];
};

export const courses: Course[] = [
    {
      id: 'ap_art_history',
      slug: 'ap-art-history',
      name: 'AP® Art History',
      description: 'Explore the history of art through critical analysis of architecture, sculpture, painting, and other artistic media.',
      icon: '/images/ap_art_history.svg',
      subject: 'Arts',
      examDate: "2026-05-14T08:00:00",
    },
    {
      id: 'ap_biology',
      slug: 'ap-biology',
      name: 'AP® Biology',
      description: 'Explore the science of life through laboratory investigations and advanced study of cellular processes, genetics, evolution, and ecology.',
      icon: '/images/ap_biology.svg',
      subject: 'Science',
      abbreviations: ['ap bio'],
      examDate: "2026-05-04T08:00:00",
    },
    {
      id: 'ap_calculus_ab',
      slug: 'ap-calculus-ab',
      name: 'AP® Calculus AB',
      description: 'Master the fundamentals of differential and integral calculus through limits, derivatives, and their applications.',
      icon: '/images/ap_calculus_ab.svg',
      subject: 'Mathematics',
      abbreviations: ['ap calc ab'],
      examDate: "2026-05-11T08:00:00",
    },
    {
      id: 'ap_calculus_bc',
      slug: 'ap-calculus-bc',
      name: 'AP® Calculus BC',
      description: 'Advanced calculus covering all AB topics plus additional techniques of integration, series, and parametric equations.',
      icon: '/images/ap_calculus_bc.svg',
      subject: 'Mathematics',
      abbreviations: ['ap calc bc'],
      examDate: "2026-05-11T08:00:00",
    },
    {
      id: 'ap_capstone_research',
      slug: 'ap-capstone-research',
      name: 'AP® Capstone Research',
      description: 'Conduct independent research on a topic of personal interest, culminating in an academic paper and presentation.',
      icon: '/images/ap_research.png',
      subject: 'Interdisciplinary',
      examDate: "2026-04-30T23:59:00",
    },
    {
      id: 'ap_capstone_seminar',
      slug: 'ap-capstone-seminar',
      name: 'AP® Capstone Seminar',
      description: 'Develop critical thinking and research skills through investigation of complex, real-world issues and problems.',
      icon: '/images/ap_seminar.svg',
      subject: 'Interdisciplinary',
      examDate: "2026-05-11T12:00:00",
    },
    {
      id: 'ap_chemistry',
      slug: 'ap-chemistry',
      name: 'AP® Chemistry',
      description: 'Dive deep into chemical reactions, atomic structure, bonding, and thermodynamics through hands-on laboratory work.',
      icon: '/images/ap_chemistry.svg',
      subject: 'Science',
      abbreviations: ['ap chem'],
      examDate: "2026-05-05T08:00:00",
    },
    {
      id: 'ap_chinese_language',
      slug: 'ap-chinese-language',
      name: 'AP® Chinese Language and Culture',
      description: 'Develop proficiency in Chinese through authentic materials and cultural exploration of Chinese-speaking regions.',
      icon: '/images/ap_chinese_language_and_culture.svg',
      subject: 'World Languages',
      examDate: "2026-05-08T12:00:00",
    },
    {
      id: 'ap_comparative_government',
      slug: 'ap-comparative-government',
      name: 'AP® Comparative Government and Politics',
      description: 'Compare political systems, institutions, and processes across different countries and regions.',
      icon: '/images/ap_comparative_government_and_politics.svg',
      subject: 'Social Studies',
      abbreviations: ['ap comp gov'],
      examDate: "2026-05-06T12:00:00",
    },
    {
      id: 'ap_computer_science_a',
      slug: 'ap-computer-science-a',
      name: 'AP® Computer Science A',
      description: 'Learn object-oriented programming in Java, including data structures, algorithms, and software design principles.',
      icon: '/images/ap_computer_science_a.svg',
      subject: 'Computer Science',
      abbreviations: ['ap csa'],
      examDate: "2026-05-15T12:00:00",
    },
    {
      id: 'ap_computer_science_principles',
      slug: 'ap-computer-science-principles',
      name: 'AP® Computer Science Principles',
      description: 'Explore the foundational concepts of computer science including programming, algorithms, and the impact of computing.',
      icon: '/images/ap_computer_science_principles.svg',
      subject: 'Computer Science',
      abbreviations: ['ap csp'],
      examDate: "2026-05-14T12:00:00",
    },
    {
      id: 'ap_english_language',
      slug: 'ap-english-language',
      name: 'AP® English Language and Composition',
      description: 'Develop advanced writing and analytical skills through the study of rhetoric, argumentation, and composition.',
      icon: '/images/ap_english_language_and_composition.svg',
      subject: 'English',
      abbreviations: ['ap lang'],
      examDate: "2026-05-13T08:00:00",
    },
    {
      id: 'ap_english_literature',
      slug: 'ap-english-literature',
      name: 'AP® English Literature and Composition',
      description: 'Analyze and interpret literature while developing sophisticated writing skills and critical thinking abilities.',
      icon: '/images/ap_english_literature_and_composition.svg',
      subject: 'English',
      abbreviations: ['ap lit'],
      examDate: "2026-05-06T08:00:00",
    },
    {
      id: 'ap_environmental_science',
      slug: 'ap-environmental-science',
      name: 'AP® Environmental Science',
      description: 'Study environmental systems, human impact on the environment, and solutions to environmental problems.',
      icon: '/images/ap_environmental_science.svg',
      subject: 'Science',
      abbreviations: ['apes'],
      examDate: "2026-05-15T08:00:00",
    },
    {
      id: 'ap_european_history',
      slug: 'ap-european-history',
      name: 'AP® European History',
      description: 'Explore European history from 1450 to present, analyzing historical documents and developing historical thinking skills.',
      icon: '/images/ap_european_history.svg',
      subject: 'Social Studies',
      abbreviations: ['ap euro'],
      examDate: "2026-05-04T12:00:00",
    },
    {
      id: 'ap_french_language',
      slug: 'ap-french-language',
      name: 'AP® French Language and Culture',
      description: 'Develop proficiency in French through authentic materials and cultural exploration of French-speaking countries.',
      icon: '/images/ap_french_language_and_culture.svg',
      subject: 'World Languages',
      examDate: "2026-05-12T08:00:00",
    },
    {
      id: 'ap_german_language',
      slug: 'ap-german-language',
      name: 'AP® German Language and Culture',
      description: 'Develop proficiency in German through authentic materials and cultural exploration of German-speaking countries.',
      icon: '/images/ap_german_language_and_culture.svg',
      subject: 'World Languages',
      examDate: "2026-05-13T08:00:00",
    },
    {
      id: 'ap_human_geography',
      slug: 'ap-human-geography',
      name: 'AP® Human Geography',
      description: 'Examine patterns and processes that shape human understanding and use of Earth at local, regional, and global scales.',
      icon: '/images/ap_human_geography.svg',
      subject: 'Social Studies',
      abbreviations: ['aphg', 'ap hug'],
      examDate: "2026-05-05T08:00:00",
    },
    {
      id: 'ap_italian_language',
      slug: 'ap-italian-language',
      name: 'AP® Italian Language and Culture',
      description: 'Develop proficiency in Italian through authentic materials and cultural exploration of Italian-speaking regions.',
      icon: '/images/ap_italian_language_and_culture.svg',
      subject: 'World Languages',
      examDate: "2026-05-08T08:00:00",
    },
    {
      id: 'ap_japanese_language',
      slug: 'ap-japanese-language',
      name: 'AP® Japanese Language and Culture',
      description: 'Develop proficiency in Japanese through authentic materials and cultural exploration of Japan.',
      icon: '/images/ap_japanese_language_and_culture.svg',
      subject: 'World Languages',
      examDate: "2026-05-12T12:00:00",
    },
    {
      id: 'ap_latin',
      slug: 'ap-latin',
      name: 'AP® Latin',
      description: 'Study Latin literature, language, and Roman culture through reading and analysis of classical texts.',
      icon: '/images/ap_latin.svg',
      subject: 'World Languages',
      examDate: "2026-05-04T08:00:00",
    },
    {
      id: 'ap_macroeconomics',
      slug: 'ap-macroeconomics',
      name: 'AP® Macroeconomics',
      description: 'Study economic principles that apply to an economy as a whole, including national income, inflation, and fiscal policy.',
      icon: '/images/ap_macroeconomics.svg',
      subject: 'Social Studies',
      abbreviations: ['ap macro'],
      examDate: "2026-05-08T12:00:00",
    },
    {
      id: 'ap_microeconomics',
      slug: 'ap-microeconomics',
      name: 'AP® Microeconomics',
      description: 'Analyze individual economic behavior, market structures, and the role of government in correcting market failures.',
      icon: '/images/ap_microeconomics.svg',
      subject: 'Social Studies',
      abbreviations: ['ap micro'],
      examDate: "2026-05-04T12:00:00",
    },
    {
      id: 'ap_music_theory',
      slug: 'ap-music-theory',
      name: 'AP® Music Theory',
      description: 'Develop skills in music composition, analysis, and aural perception through study of musical elements and structures.',
      icon: '/images/ap_music_theory.svg',
      subject: 'Arts',
      examDate: "2026-05-11T12:00:00",
    },
    {
      id: 'ap_physics_1',
      slug: 'ap-physics-1',
      name: 'AP® Physics 1',
      description: 'Explore mechanics, waves, and sound through inquiry-based laboratory investigations and mathematical analysis.',
      icon: '/images/ap_physics_1_algebra_based.svg',
      subject: 'Science',
      examDate: "2026-05-06T12:00:00",
    },
    {
      id: 'ap_physics_2',
      slug: 'ap-physics-2',
      name: 'AP® Physics 2',
      description: 'Study electricity, magnetism, optics, thermodynamics, and modern physics through hands-on experiments.',
      icon: '/images/ap_physics_2_algebra_based.svg',
      subject: 'Science',
      examDate: "2026-05-07T08:00:00",
    },
    {
      id: 'ap_physics_c_mechanics',
      slug: 'ap-physics-c-mechanics',
      name: 'AP® Physics C: Mechanics',
      description: 'Advanced calculus-based study of classical mechanics including kinematics, dynamics, and energy conservation.',
      icon: '/images/ap_physics_c_mechanics.svg',
      subject: 'Science',
      examDate: "2026-05-13T12:00:00",
    },
    {
      id: 'ap_physics_c_electricity_magnetism',
      slug: 'ap-physics-c-electricity-magnetism',
      name: 'AP® Physics C: Electricity & Magnetism',
      description: 'Calculus-based exploration of electric fields, magnetic fields, and electromagnetic induction.',
      icon: '/images/ap_physics_c_electricity_and_magnetism.svg',
      subject: 'Science',
      examDate: "2026-05-14T12:00:00",
    },
    {
      id: 'ap_precalculus',
      slug: 'ap-precalculus',
      name: 'AP® Precalculus',
      description: 'Build mathematical foundation for calculus through functions, trigonometry, and analytical geometry.',
      icon: '/images/ap_precalculus.svg',
      subject: 'Mathematics',
      abbreviations: ['ap precalc'],
      examDate: "2026-05-12T08:00:00",
    },
    {
      id: 'ap_psychology',
      slug: 'ap-psychology',
      name: 'AP® Psychology',
      description: 'Examine human behavior and mental processes through scientific methods and psychological perspectives.',
      icon: '/images/ap_psychology.svg',
      subject: 'Social Studies',
      abbreviations: ['ap psych'],
      examDate: "2026-05-12T12:00:00",
    },
    {
      id: 'ap_spanish_language',
      slug: 'ap-spanish-language',
      name: 'AP® Spanish Language and Culture',
      description: 'Develop proficiency in Spanish through authentic materials and cultural exploration of Spanish-speaking countries.',
      icon: '/images/ap_spanish_language_and_culture.svg',
      subject: 'World Languages',
      examDate: "2026-05-14T08:00:00",
    },
    {
      id: 'ap_spanish_literature',
      slug: 'ap-spanish-literature',
      name: 'AP® Spanish Literature and Culture',
      description: 'Analyze Spanish and Latin American literary works while developing advanced language skills.',
      icon: '/images/ap_spanish_literature_and_culture.svg',
      subject: 'World Languages',
      examDate: "2026-05-13T12:00:00",
    },
    {
      id: 'ap_statistics',
      slug: 'ap-statistics',
      name: 'AP® Statistics',
      description: 'Learn statistical concepts and methods for collecting, analyzing, and interpreting data in real-world contexts.',
      icon: '/images/ap_statistics.svg',
      subject: 'Mathematics',
      abbreviations: ['ap stats'],
      examDate: "2026-05-07T12:00:00",
    },
    {
      id: 'ap_united_states_government_politics',
      slug: 'ap-united-states-government-politics',
      name: 'AP® U.S. Government and Politics',
      description: 'Study the American political system, constitutional principles, and the role of citizens in democratic society.',
      icon: '/images/ap_united_states_government_and_politics.svg',
      subject: 'Social Studies',
      abbreviations: ['ap gov'],
      examDate: "2026-05-05T12:00:00",
    },
    {
      id: 'ap_us_history',
      slug: 'ap-us-history',
      name: 'AP® U.S. History',
      description: 'Examine American history from pre-Columbian times to present, developing historical analysis and writing skills.',
      icon: '/images/ap_united_states_history.svg',
      subject: 'Social Studies',
      abbreviations: ['apush'],
      examDate: "2026-05-08T08:00:00",
    },
    {
      id: 'ap_world_history',
      slug: 'ap-world-history',
      name: 'AP® World History: Modern',
      description: 'Explore global historical processes and connections from 1200 CE to present across different civilizations.',
      icon: '/images/ap_world_history_modern.svg',
      subject: 'Social Studies',
      abbreviations: ['ap world'],
      examDate: "2026-05-07T08:00:00",
    },
    {
      id: 'ap_business_principles_personal_finance',
      slug: 'ap-business-principles-personal-finance',
      name: 'AP® Business Principles/Personal Finance',
      description: 'Master essential business concepts and develop personal financial literacy skills for real-world application.',
      icon: '💼',
      subject: 'Social Studies',
      examDate: "2026-05-15T12:00:00",
      comingSoon: true,
    },
    {
      id: 'ap_cybersecurity',
      slug: 'ap-cybersecurity',
      name: 'AP® Cybersecurity',
      description: 'Explore the principles of cybersecurity, including threats, vulnerabilities, and the tools to protect digital assets.',
      icon: '🛡️',
      subject: 'Computer Science',
      examDate: "2026-05-15T12:00:00",
      comingSoon: true,
    },
    {
      id: 'honors_algebra_ii',
      slug: 'honors-algebra-ii',
      name: 'Honors Algebra II',
      description: 'An advanced study of algebraic concepts including functions, polynomials, and complex numbers.',
      icon: '📈',
      subject: 'Mathematics',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'honors_biology',
      slug: 'honors-biology',
      name: 'Honors Biology',
      description: 'An in-depth exploration of biological systems, from molecular biology to ecology, with an emphasis on inquiry-based learning.',
      icon: '🧬',
      subject: 'Science',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'honors_chemistry',
      slug: 'honors-chemistry',
      name: 'Honors Chemistry',
      description: 'A rigorous introduction to chemical principles, including atomic theory, stoichiometry, and thermodynamics.',
      icon: '🧪',
      subject: 'Science',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'honors_economics',
      slug: 'honors-economics',
      name: 'Honors Economics',
      description: 'A comprehensive study of microeconomic and macroeconomic principles and their application to real-world scenarios.',
      icon: '💹',
      subject: 'Social Studies',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'honors_physics',
      slug: 'honors-physics',
      name: 'Honors Physics',
      description: 'An accelerated study of classical and modern physics, focusing on mechanics, electricity, and magnetism.',
      icon: '⚛️',
      subject: 'Science',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'honors_pre_calculus',
      slug: 'honors-pre-calculus',
      name: 'Honors Pre-Calculus',
      description: 'Preparation for calculus through an advanced study of functions, trigonometry, and analytic geometry.',
      icon: '📐',
      subject: 'Mathematics',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'honors_statistics',
      slug: 'honors-statistics',
      name: 'Honors Statistics',
      description: 'An advanced introduction to the major concepts and tools for collecting, analyzing, and drawing conclusions from data.',
      icon: '📊',
      subject: 'Mathematics',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'honors_us_government',
      slug: 'honors-us-government',
      name: 'Honors US Government',
      description: 'A detailed analysis of the United States government and political system, including its constitutional underpinnings.',
      icon: '🗳️',
      subject: 'Social Studies',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'honors_us_history',
      slug: 'honors-us-history',
      name: 'Honors US History',
      description: 'A comprehensive and in-depth survey of American history from the colonial period to the present.',
      icon: '🇺🇸',
      subject: 'Social Studies',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'honors_world_history',
      slug: 'honors-world-history',
      name: 'Honors World History',
      description: 'An advanced study of global history, examining patterns of change and continuity across different cultures and eras.',
      icon: '🌎',
      subject: 'Social Studies',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'academic_decathlon',
      slug: 'academic-decathlon',
      name: 'Academic Decathlon',
      description: 'A team-based academic competition where students match their intellects with students from other schools.',
      icon: '🏆',
      subject: 'Academic Electives',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'creative_writing',
      slug: 'creative-writing',
      name: 'Creative Writing',
      description: 'Students will develop their writing skills through the study of various literary forms and genres.',
      icon: '✍️',
      subject: 'Academic Electives',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'critical_thinking',
      slug: 'critical-thinking',
      name: 'Critical Thinking',
      description: 'This course introduces students to the principles of critical thinking and logic.',
      icon: '🤔',
      subject: 'Academic Electives',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'debate_1',
      slug: 'debate-1',
      name: 'Debate I',
      description: 'This course provides an introduction to the principles and practices of formal debate.',
      icon: '🗣️',
      subject: 'Academic Electives',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'debate_2',
      slug: 'debate-2',
      name: 'Debate II Honors',
      description: 'This course expands on the principles of debate, focusing on advanced strategies and different debate formats.',
      icon: '🗣️',
      subject: 'Academic Electives',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'debate_3',
      slug: 'debate-3',
      name: 'Debate III Honors',
      description: 'Focuses on competitive debate theory and practice, including in-depth research and case writing.',
      icon: '🗣️',
      subject: 'Academic Electives',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'debate_4',
      slug: 'debate-4',
      name: 'Debate IV Honors',
      description: 'The capstone course for advanced debaters, focusing on leadership, coaching, and tournament direction.',
      icon: '🗣️',
      subject: 'Academic Electives',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'digital_art_design',
      slug: 'digital-art-design',
      name: 'Digital Art & Design',
      description: 'This course provides an introduction to the principles of digital art and design.',
      icon: '🎨',
      subject: 'Academic Electives',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'film_studies',
      slug: 'film-studies',
      name: 'Film Studies',
      description: 'This course provides an introduction to the analysis of film as an art form.',
      icon: '🎬',
      subject: 'Academic Electives',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'intro_business_entrepreneurship',
      slug: 'intro-business-entrepreneurship',
      name: 'Introduction to Business & Entrepreneurship',
      description: 'This course provides an overview of the business world and the entrepreneurial process.',
      icon: '🚀',
      subject: 'Academic Electives',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'intro_computer_science',
      slug: 'intro-computer-science',
      name: 'Introduction to Computer Science',
      description: 'This course provides an introduction to the fundamental concepts of computer science.',
      icon: '💻',
      subject: 'Academic Electives',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'intro_engineering_design',
      slug: 'intro-engineering-design',
      name: 'Introduction to Engineering Design',
      description: 'This course provides an introduction to the engineering design process.',
      icon: '⚙️',
      subject: 'Academic Electives',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'journalism_1',
      slug: 'journalism-1',
      name: 'Journalism I',
      description: 'This course provides an introduction to the principles and practices of journalism.',
      icon: '📰',
      subject: 'Academic Electives',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'journalism_2',
      slug: 'journalism-2',
      name: 'Journalism II Honors',
      description: 'This course focuses on advanced reporting, feature writing, and multimedia journalism.',
      icon: '📰',
      subject: 'Academic Electives',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'journalism_3',
      slug: 'journalism-3',
      name: 'Journalism III Honors',
      description: 'This course focuses on investigative journalism, data journalism, and media ethics.',
      icon: '📰',
      subject: 'Academic Electives',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'journalism_4',
      slug: 'journalism-4',
      name: 'Journalism IV Honors',
      description: 'The capstone course for advanced student journalists, focusing on editorial leadership and publication management.',
      icon: '📰',
      subject: 'Academic Electives',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'mythology',
      slug: 'mythology',
      name: 'Mythological Studies',
      description: 'This course introduces students to the myths and legends of various cultures.',
      icon: '🏛️',
      subject: 'Academic Electives',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'peer_leadership',
      slug: 'peer-leadership',
      name: 'Peer Leadership',
      description: 'This course provides students with the skills and knowledge to be effective peer leaders.',
      icon: '🤝',
      subject: 'Academic Electives',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'philosophy',
      slug: 'philosophy',
      name: 'Philosophy',
      description: 'This course provides an introduction to the fundamental questions of philosophy.',
      icon: '🧠',
      subject: 'Academic Electives',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'public_speaking',
      slug: 'public-speaking',
      name: 'Public Speaking',
      description: 'This course provides students with the skills and confidence to be effective public speakers.',
      icon: '🎤',
      subject: 'Academic Electives',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'robotics',
      slug: 'robotics',
      name: 'Robotics',
      description: 'This course provides an introduction to the principles of robotics and automation.',
      icon: '🤖',
      subject: 'Academic Electives',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'sat_act_preparation',
      slug: 'sat-act-preparation',
      name: 'SAT/ACT Preparation',
      description: 'This course prepares students for the SAT and ACT college entrance exams.',
      icon: '📝',
      subject: 'Academic Electives',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'sociology',
      slug: 'sociology',
      name: 'Sociology',
      description: 'This course provides an introduction to the study of human society and social behavior.',
      icon: '👥',
      subject: 'Academic Electives',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'student_government',
      slug: 'student-government',
      name: 'Student Government',
      description: 'This course provides students with the opportunity to participate in the governance of their school.',
      icon: '🏛️',
      subject: 'Academic Electives',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'web_development',
      slug: 'web-development',
      name: 'Web Development',
      description: 'This course provides an introduction to the principles and practices of web development.',
      icon: '🌐',
      subject: 'Academic Electives',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'yearbook',
      slug: 'yearbook',
      name: 'Yearbook',
      description: 'This course provides students with the opportunity to create and publish their school\'s yearbook.',
      icon: '📖',
      subject: 'Academic Electives',
      examDate: "2026-05-20T12:00:00",
      comingSoon: true,
    },
    {
      id: 'english_1',
      slug: 'english-1',
      name: 'English I',
      description: 'Focuses on foundational reading, writing, and analytical skills through a variety of literary and informational texts.',
      icon: '📚',
      subject: 'English',
      abbreviations: ['english 1'],
      examDate: '2026-05-20T12:00:00',
      comingSoon: true,
    },
    {
      id: 'english_1_honors',
      slug: 'english-1-honors',
      name: 'English I Honors',
      description: 'An accelerated and in-depth study of foundational literary analysis and composition for advanced students.',
      icon: '📚',
      subject: 'English',
      abbreviations: ['english 1 honors'],
      examDate: '2026-05-20T12:00:00',
      comingSoon: true,
    },
    {
      id: 'english_2',
      slug: 'english-2',
      name: 'English II',
      description: 'Builds on foundational skills with a focus on world literature and comparative analysis.',
      icon: '📚',
      subject: 'English',
      abbreviations: ['english 2'],
      examDate: '2026-05-20T12:00:00',
      comingSoon: true,
    },
    {
      id: 'english_2_honors',
      slug: 'english-2-honors',
      name: 'English II Honors',
      description: 'An accelerated and in-depth study of world literature with an emphasis on critical theory and complex texts.',
      icon: '📚',
      subject: 'English',
      abbreviations: ['english 2 honors'],
      examDate: '2026-05-20T12:00:00',
      comingSoon: true,
    },
    {
      id: 'english_3',
      slug: 'english-3',
      name: 'English III',
      description: 'Focuses on American literature, exploring how historical and cultural movements have shaped the nation\'s literary voice.',
      icon: '📚',
      subject: 'English',
      abbreviations: ['english 3'],
      examDate: '2026-05-20T12:00:00',
      comingSoon: true,
    },
    {
      id: 'english_3_honors',
      slug: 'english-3-honors',
      name: 'English III Honors',
      description: 'An accelerated survey of American literature, preparing students for the rigor of AP English courses.',
      icon: '📚',
      subject: 'English',
      abbreviations: ['english 3 honors'],
      examDate: '2026-05-20T12:00:00',
      comingSoon: true,
    },
    {
      id: 'english_4',
      slug: 'english-4',
      name: 'English IV',
      description: 'Focuses on British literature, tracing its development from the Anglo-Saxon period to the modern era.',
      icon: '📚',
      subject: 'English',
      abbreviations: ['english 4'],
      examDate: '2026-05-20T12:00:00',
      comingSoon: true,
    },
    {
      id: 'english_4_honors',
      slug: 'english-4-honors',
      name: 'English IV Honors',
      description: 'An accelerated and in-depth study of British literature, preparing students for college-level literary analysis.',
      icon: '📚',
      subject: 'English',
      abbreviations: ['english 4 honors'],
      examDate: '2026-05-20T12:00:00',
      comingSoon: true,
    }
];

// Re-exporting these types as they are no longer defined here.
export type { Flashcard, Question, Unit } from './course-data';
