
import { type ThemeVariant, type PresetColorDefinition } from './ThemeManager';

export type Preset = {
    id: string;
    name: string;
    category: 'Special Edition' | 'Light' | 'Dark' | 'Gaming' | 'Pixel Art' | 'Seasonal' | 'Scenic';
    hasFullScreenBackground?: boolean;
    backgroundImage?: string;
    previewType?: 'gradient' | 'image' | 'stars' | 'video';
    tags?: string[];
    variants?: ThemeVariant[];
    colors: PresetColorDefinition;
};

// --- THIS IS THE NEW, ACCURATE "STARRY NIGHT" THEME DEFINITION ---
const starryNightTheme: Preset = {
    id: 'starry-night',
    name: '✨ Starry Night',
    category: 'Special Edition',
    hasFullScreenBackground: true,
    previewType: 'stars',
    tags: ['popular', 'animated', 'cool'],
    colors: { // Base/Classic variant colors
      primaryGradientStart: '#000000',
      primaryGradientEnd: '#142b44',
      background: '#152238',
      foreground: '#FFFFFF',
      primary: '#89ddff',
      secondary: '#191919',
      accent: '#e1adff',
      card: '#152238',
      muted: '#191919',
      border: '#30363d',
      input: '#191919',
      ring: '#89ddff',
      starColor: '#FFFFFF',
      mutedForeground: '#ADB5BD',
    },
    variants: [
      {
        id: 'classic',
        name: 'Classic',
        colors: {
          primaryGradientStart: '#000000',
          primaryGradientEnd: '#142b44',
          background: '#152238',
          foreground: '#FFFFFF',
          primary: '#89ddff',
          secondary: '#191919',
          accent: '#e1adff',
          card: '#152238',
          muted: '#191919',
          mutedForeground: '#ADB5BD',
          border: '#30363d',
          input: '#191919',
          ring: '#89ddff',
          starColor: '#FFFFFF',
        }
      },
      {
        id: 'cotton-candy',
        name: '🍭 Cotton Candy Sky',
        colors: {
          primaryGradientStart: '#ff71b2',
          primaryGradientEnd: '#509be1',
          background: '#9f45b0',
          foreground: '#ffffff',
          primary: '#d3e9ff',
          secondary: '#a763b6',
          accent: '#7f78be',
          card: '#9f45b0',
          muted: '#a763b6',
          mutedForeground: '#fff4f4',
          border: '#a763b6',
          input: '#a763b6',
          ring: '#d3e9ff',
          starColor: '#FFFFFF',
        },
      },
      {
        id: 'forest',
        name: '🌲 Forest Night',
        colors: {
          primaryGradientStart: '#000000',
          primaryGradientEnd: '#14442b',
          background: '#011502',
          foreground: '#ffffff',
          primary: '#c4c6ff',
          secondary: '#191919',
          accent: '#77be80',
          card: '#011502',
          muted: '#191919',
          mutedForeground: '#DBF9F4',
          border: '#191919',
          input: '#191919',
          ring: '#c4c6ff',
          starColor: '#FFFFFF',
        },
      },
      {
        id: 'galaxy',
        name: '🔮 Galaxy Dream',
        colors: {
          primaryGradientStart: '#00076f',
          primaryGradientEnd: '#b133c9',
          background: '#9f45b0',
          foreground: '#ffe4f2',
          primary: '#fff3c4',
          secondary: '#9d00ff',
          accent: '#9d00ff',
          card: '#9f45b0',
          muted: '#9d00ff',
          mutedForeground: '#FFFFFF',
          border: '#9d00ff',
          input: '#9d00ff',
          ring: '#fff3c4',
          starColor: '#FFFFFF',
        },
      },
       {
        id: 'amber-horizon',
        name: '🟠 Amber Horizon',
        colors: {
          primaryGradientStart: '#000000',
          primaryGradientEnd: '#e69138',
          background: '#e69138',
          foreground: '#FFFFFF',
          primary: '#fbe39b',
          secondary: '#191919',
          accent: '#e06666',
          card: '#c37728',
          muted: '#191919',
          mutedForeground: '#FFFFFF',
          border: '#e69138',
          input: '#191919',
          ring: '#fbe39b',
          starColor: '#ffe234',
        },
      },
      {
        id: 'twilight-sky',
        name: '🏙️ Twilight Sky',
        colors: {
          primaryGradientStart: '#1e48a9',
          primaryGradientEnd: '#62cff4',
          background: '#6b94f5',
          foreground: '#FFFFFF',
          primary: '#FFF3C4',
          secondary: '#95b3f8',
          accent: '#aac2f9',
          card: '#6b94f5',
          muted: '#95b3f8',
          mutedForeground: '#040a18',
          border: '#aac2f9',
          input: '#95b3f8',
          ring: '#FFF3C4',
          starColor: '#FFFFFF',
        },
      },
      {
        id: 'sunrise-fade',
        name: '🌅 Sunrise Fade',
        colors: {
          primaryGradientStart: '#FFAE41',
          primaryGradientEnd: '#F83D41',
          background: '#C49C48',
          foreground: '#FFFFFF',
          primary: '#FFF3C4',
          secondary: '#191919',
          accent: '#C49C48',
          card: '#C49C48',
          muted: '#191919',
          mutedForeground: '#E0E0E0',
          border: '#C49C48',
          input: '#C49C48',
          ring: '#FFF3C4',
          starColor: '#FFFFFF',
        },
      },
    ]
  };

export const THEME_PRESETS: Preset[] = [
  starryNightTheme,
  {
    id: 'parisian-daydream',
    name: '🎨 Parisian Daydream',
    category: 'Special Edition',
    hasFullScreenBackground: true,
    previewType: 'video',
    tags: ['preppy', 'girly', 'aesthetic'],
    colors: {
      background: '#fdeef1',
      foreground: '#d35867',
      primary: '#d35867',
      secondary: '#f9d8e1',
      accent: '#8eb2c7',
      card: '#f9d8e1',
      muted: '#f5c6d3',
      border: '#efb9c8',
      input: '#f5c6d3',
      ring: '#d35867',
      mutedForeground: '#ab7886',
    }
  },
  {
    id: 'tidal-bloom',
    name: '🌊 Tidal Bloom',
    category: 'Scenic',
    hasFullScreenBackground: true,
    tags: ['aesthetic', 'preppy', 'cozy'],
    colors: {
      background: '#fdf6e3', 
      foreground: '#5d4037', 
      primary: '#3b82f6',    
      secondary: '#f7f0e0',  
      accent: '#ff8c69',     
      card: '#fdfbf5',       
      muted: '#f0e9d6',      
      border: '#e6dcc9',     
      input: '#f0e9d6',       
      ring: '#3b82f6',       
      mutedForeground: '#8c7a65', 
      primaryGradientStart: '#a8edea',
      primaryGradientEnd: '#f7d794',
    },
   },
  {
    id: 'forest-haze',
    name: '🌲 Forest Haze',
    category: 'Scenic',
    hasFullScreenBackground: true,
    tags: ['cozy', 'cool'],
    colors: {
      background: '#0b2e22',
      foreground: '#d4e0d9',
      primary: '#52a379',
      secondary: '#163e30',
      accent: '#a3b18a',
      card: '#163e30',
      muted: '#214d3f',
      border: '#2a5c4d',
      input: '#214d3f',
      ring: '#52a379',
    }
  },
  {
    id: 'midnight-office',
    name: '🌃 Midnight Office',
    category: 'Scenic',
    hasFullScreenBackground: true,
    backgroundImage: '/images/theme/living_room.gif',
    previewType: 'image',
    tags: ['cozy', 'animated', 'lofi'],
    colors: {
      primaryGradientStart: '#0c2434',
      primaryGradientEnd: '#0c2434',
      background: '#0c2434',
      foreground: '#cceeee',
      primary: '#d9444f',
      secondary: '#1e4966',
      accent: '#33cccc',
      card: '#14364e',
      muted: '#2d5a78',
      border: '#28516d',
      input: '#14364e',
      ring: '#d9444f',
    }
  },
   {
    id: 'pastel-soft',
    name: '🌸 Pastel Soft',
    category: 'Light',
    hasFullScreenBackground: true,
    tags: ['girly', 'aesthetic', 'preppy'],
    colors: {
      background: '#fffbf7',
      foreground: '#6b4e3d',
      primary: '#ffb6c1',
      secondary: '#ffeef2',
      accent: '#98d8c8',
      card: '#ffffff',
      muted: '#ffeef2',
      border: '#f7c2cc',
      input: '#ffeef2',
      ring: '#ffb6c1',
    },
   },
  {
    id: 'cloudy-cocoa',
    name: '☁️ Cloudy Cocoa',
    category: 'Light',
    colors: {
      background: '#917156',
      foreground: '#2b1c1c',
      primary: '#5a3b2e',
      secondary: '#7e5c45',
      accent: '#4b3621',
      card: '#a88a72',
      muted: '#7b5c49',
      border: '#5a3b2e',
      input: '#7c5f4a',
      ring: '#4b3621',
    },
  },
  {
    id: 'matcha-study',
    name: '🍵 Matcha Study',
    category: 'Light',
    tags: ['cozy', 'aesthetic'],
    colors: {
      background: '#e0f2e9',
      foreground: '#1b4332',
      primary: '#95d5b2',
      secondary: '#b7e4c7',
      accent: '#74c69d',
      card: '#ffffff',
      muted: '#cfe7d6',
      border: '#a3cbb3',
      input: '#bce0cd',
      ring: '#95d5b2',
    },
  },
  {
    id: 'pink-aesthetic',
    name: '🌸 Pink Aesthetic',
    category: 'Light',
    tags: ['popular', 'girly', 'aesthetic'],
    colors: {
      background: '#F8C2D4',
      foreground: '#9C425C',
      primary: '#9A2D4A',
      secondary: '#F8C2D4',
      accent: '#FF6384',
      card: '#fdeaf1',
      muted: '#FFE4E1',
      border: '#f0b8c8',
      input: '#F7AEC1',
      ring: '#9A2D4A',
      mutedForeground: '#ab7886',
    },
  },
  {
    id: 'fc-barcelona',
    name: 'FC Barcelona 🐐',
    category: 'Gaming',
    hasFullScreenBackground: true,
    previewType: 'gradient',
    tags: ['sports', 'gaming', 'cool'],
    colors: {
      primaryGradientStart: '#A50044',
      primaryGradientEnd: '#004D98',
      background: '#1A2B3C',
      foreground: '#FFFFFF',
      primary: '#A50044',
      secondary: '#1A2B3C',
      accent: '#004D98',
      card: '#1A2B3C',
      muted: '#003B73',
      border: '#003B73',
      input: '#003B73',
      ring: '#EDBB00',
      mutedForeground: '#E0E0E0',
    }
  },
  {
    id: 'catpuccin',
    name: '🐾 Catpuccin',
    category: 'Dark',
    hasFullScreenBackground: true,
    backgroundImage: '/images/theme/catpuccin.png',
    previewType: 'image',
    tags: ['popular', 'cozy', 'aesthetic'],
    colors: {
      primaryGradientStart: '#23212e',
      primaryGradientEnd: '#23212e',
      background: '#23212e',
      foreground: '#e2e0ee',
      primary: '#b693ce',
      secondary: '#302e42',
      accent: '#997aae',
      card: '#2a2739',
      muted: '#39364c',
      border: '#434059',
      input: '#39364c',
      ring: '#b693ce',
    },
  },
  {
    id: 'cosmic-grape',
    name: '🍇 Cosmic Grape',
    category: 'Dark',
    tags: ['aesthetic', 'cool'],
    colors: {
      background: '#231942',
      foreground: '#f1f1f1',
      primary: '#be95c4',
      secondary: '#5e548e',
      accent: '#9f86c0',
      card: '#2c2250',
      muted: '#3c316f',
      border: '#4a3d8a',
      input: '#3c316f',
      ring: '#be95c4',
    },
  },
  {
    id: 'obsidian-mind',
    name: '🪨 Obsidian Mind',
    category: 'Dark',
    colors: {
      primaryGradientStart: '#0a0a0a',
      primaryGradientEnd: '#0a0a0a',
      background: '#0a0a0a',
      foreground: '#f5f5f5',
      primary: '#e5e5e5',
      secondary: '#111111',
      accent: '#555555',
      card: '#1a1a1a',
      muted: '#555555',
      border: '#2e2e2e',
      input: '#2a2a2a',
      ring: '#e5e5e5',
    },
  },
  {
    id: 'hacker-terminal',
    name: '📟 Hacker Terminal',
    category: 'Gaming',
    tags: ['gaming', 'cool'],
    colors: {
      background: '#000000',
      foreground: '#00ff00',
      primary: '#00ff00',
      secondary: '#1a1a1a',
      accent: '#00aa00',
      card: '#0a0a0a',
      muted: '#1f1f1f',
      border: '#2e2e2e',
      input: '#1a1a1a',
      ring: '#00ff00',
    },
  },
  {
    id: 'frostbite-winter',
    name: '❄️ Frostbite Winter',
    category: 'Seasonal',
    hasFullScreenBackground: true,
    colors: {
      background: '#e0f7fa',
      foreground: '#004d40',
      primary: '#81d4fa',
      secondary: '#b2ebf2',
      accent: '#00bcd4',
      card: '#ffffff',
      muted: '#d0f0f3',
      border: '#a2d9e4',
      input: '#c9f2f9',
      ring: '#81d4fa',
    },
  },
];
