
'use client';

import React, { useEffect, useMemo } from 'react';

// This is a global type, but it's safer to declare it here
declare global {
    interface Window {
        katex: {
            renderToString(tex: string, options?: any): string;
        };
    }
}

// This component now uses katex to render math expressions.
// It uses a regex to find all math expressions (both inline and block)
// and replaces them with the HTML generated by KaTeX.
export function MathRenderer({ content }: { content: string | null | undefined }) {
  const processedContent = useMemo(() => {
    if (!content || typeof window === 'undefined' || !window.katex) {
      return content || '';
    }
    
    // Regex to find all math expressions, including nested ones
    const regex = /(\$\$[\s\S]*?\$\$|\$[^$]+\$)/g;

    return content.replace(regex, (match) => {
        try {
            const isDisplayMode = match.startsWith('$$');
            const tex = match.substring(isDisplayMode ? 2 : 1, match.length - (isDisplayMode ? 2 : 1));
            return window.katex.renderToString(tex, {
                displayMode: isDisplayMode,
                throwOnError: false // Prevents crashing on invalid KaTeX
            });
        } catch (error) {
            console.error('KaTeX rendering error:', error);
            return match; // Return original text on error
        }
    });

  }, [content]);

  if (!processedContent) {
    return null;
  }
  
  return (
    <div 
      className="inline-math-wrapper [&_.katex]:bg-blue-950/30 [&_.katex]:px-1.5 [&_.katex]:py-0.5 [&_.katex]:rounded dark:[&_.katex]:bg-blue-950/50"
      dangerouslySetInnerHTML={{ __html: processedContent }} 
    />
  );
}
